// /components/Traits.js

// A library of reusable style presets for special characters.
export const specialStyles = {
  Ssmall: {textShadow: 'none', fontSize: '0.5em', position: 'relative', top: '-7px', left: '-2px'},
  Lsmall: {textShadow: 'none', fontSize: '0.55em', position: 'relative', top: '-7px', left: '-2px'},
  default: {textShadow: 'none', fontSize: '0.6em', position: 'relative', top: '-7px', left: '-2px'},
  Smedium: {textShadow: 'none', fontSize: '0.65em', position: 'relative', top: '-7px', left: '-2px'},
  Mmedium: {textShadow: 'none', fontSize: '0.7em', position: 'relative', top: '-7px', left: '-2px'},
  Lmedium: {textShadow: 'none', fontSize: '0.75em', position: 'relative', top: '-7px', left: '-2px'},
  XLmedium: {textShadow: 'none', fontSize: '0.8em', position: 'relative', top: '-7px', left: '-2px'},
  Slarge: {textShadow: 'none', fontSize: '0.85em', position: 'relative', top: '-7px', left: '-2px'},
  Mlarge: {textShadow: 'none', fontSize: '0.9em', position: 'relative', top: '-7px', left: '-2px'},
  Llarge: {textShadow: 'none', fontSize: '0.95em', position: 'relative', top: '-7px', left: '-2px'},
  XLlarge: {textShadow: 'none', fontSize: '1em', position: 'relative', top: '-7px', left: '-2px'},
};

// A map that links an outfit's name to a style preset from the library above.
export const outfitStyleMap = {
    'Kimono': 'default',
    'Skull': 'default',
    'Peace': 'Mmedium',
    'Farcaster': 'default',
    'Rocket': 'default',
    'Snowflake': 'Mmedium',
    'Invader': 'default',
    'Atom': 'Lmedium',
    'Swords': 'XLmedium',
    'Biohazard': 'Smedium',
    'Trident': 'default',
    'Anchor': 'Mlarge',
    'Diamond': 'default',
    'Fireball': 'default',
    'Yin Yang': 'Mmedium',
    'Crown': 'default',
    'Love': 'Smedium',
    'Radioactive': 'Lmedium',
    'Fleur-de-lis': 'Mmedium',
    'Volcano': 'default',
    'Paw': 'default',
    'Shamrock': 'Lmedium',
    'Wave': 'default',
    'Bowtie': 'XLlarge',
    'Coffee': 'Lmedium',
    'Pizza': 'default',
    'Cookie': 'default',
    'Poison': 'default',
    'Cactus': 'default',
    'Mushroom': 'default',
    'Turtle': 'default',
    'Octopus': 'default',
    'Palette': 'default',
    'Donut': 'default',
    'Gift': 'default',
    'Lollipop': 'default',
    'Bomb': 'default',
    'Hurricane': 'default',
    'Trophy': 'default',
    'Banana': 'default',
    'Pineapple': 'default',
    'Rainbow': 'default',
    'Gamer': 'default',
    'Crystal Ball': 'default',
    'Billiards': 'default',
    'Baseball': 'Mmedium',
    'Sax': 'default',
    'Guitar': 'default',
    'Ghost': 'default',
    'Pumpkin': 'default',
    'Money': 'default',
    'Flag': 'default',
    'Birthday': 'default',
    'Bowling': 'default',
    'Target': 'default',
    'Ring': 'default',
    'Ice Cream': 'default',
    'Alien': 'default',
};

export const Traits = {
  EarsTop: {
    'None': '',
    'Pointy': '^   ^',
    'Elven': '<   >',
    'Type 3': 'v   v',
    'Antennas': 'q   p',
    'Type 5': '\\/   \\/',
    'Type 6': '/\\   /\\',
  },
  EarsHead: {
    'None': '',
    'Pointy': '^   ^',
    'Elven': '<   >',
    'Type 3': 'v   v',
    'Antennas': 'q   p',
    'Type 5': '\\/   \\/',
    'Type 6': '/\\   /\\',
  },
  Headwear: {
    'None': '',
    'Punk': '///',
    'Unicorn': '_/_',
    'Horns': '/-/',
    'Curly hair': '~~~',
    'Bald': '___',
  },
  Eyes: {
    'None': '',
    'Glasses': 'o-o',
    'Meth (Suspicious)': 'o 0',
    'Sleeping': '- -',
    'Eyes Open': 'o o',
    'Wide-Eyed': '0 0',
  },
  Nose: {
    'None': '',
    'Round': 'o',
    'Dog': 'Y',
    'Crest': '.',
    'More': '_',
  },
  Snout: {
    'None': '',
    'Normal': '---',
    'Monster': 'vvv',
    'Cigarette': '--,',
    'Wolf': 'o',
  },
  Outfit: {
    'None': '',
    'Muscular': '=|=',
    'Suit': '\\:/',
    'Priest': '\\+/',
    'Tuxedo': '\\~/',
	'Jester Collar': '/|\\',
	'Shirt': ' :~',
	'Armor': '[#]',
	'Scarf': '_w_',
	'Tie': '_v_',
	'Medallion': '_0_',
	'Vest': 'IVI',
	'Turtleneck': '_T_',
	'V-Neck': '_V_',
	'Toga': '/~/',
	'Sweater': 'x-x',
	'Collar': '_^_',
	'Kimono': '/🌸\\',
	'Skull': '\\💀/',
	'Peace': '_☮_',
	'Farcaster': '|🏰|',
	'Rocket': '/🚀/',
	'Snowflake': '_❄️_',
	'Invader': '[👾]',
	'Atom': '_⚛️_',
	'Swords': '_⚔️_',
	'Biohazard': '(☣️)',
	'Trident': '_🔱_',
	'Anchor': 'I⚓️I',
	'Diamond': '_💎_',
	'Fireball': '_🔥_',
	'Yin Yang': '(☯)',
	'Crown': 'I👑I',
	'Love': '_❤︎_',
	'Radioactive': '/☢️/',
	'Fleur-de-lis': '_⚜️_',
	'Volcano': '_🌋_',
	'Paw': '_🐾_',
	'Shamrock': '_☘︎_',
	'Wave': '_🌊_',
	'Bowtie': '|⑅|',
	'Coffee': '_☕️_',
	'Pizza': '_🍕_',
	'Cookie': '_🍪_',
	'Poison': '\\☠/',
	'Cactus': '_🌵_',
	'Mushroom': '{🍄}',
	'Turtle': '_🐢_',
	'Octopus': '_🐙_',
	'Palette': '_🎨_',
	'Donut': '[🍩]',
	'Gift': '_🎁_',
	'Lollipop': '_🍭_',
	'Bomb': '_💣_',
	'Hurricane': '(🌀)',
	'Trophy': '_🏆_',
	'Banana': '_🍌_',
	'Pineapple': '_🍍_',
	'Rainbow': '/🌈\\',
	'Gamer': '_🎮_',
	'Crystal Ball': '-🔮-',
	'Billiards': '|🎱|',
	'Baseball': '_⚾_',
	'Sax:': '_🎷_',
	'Guitar': '_🎸_',
	'Ghost': '\\👻\\',
	'Pumpkin': '_🎃_',
	'Money': '\\💸/',
	'Flag': '_🏁_',
	'Birthday': '_🎂_',
	'Bowling': '_🎳_',
	'Target': '-🎯-',
	'Ring': '_💍_',
	'Ice Cream': '_🍦_',
	'Alien': '[👽]',
  },
  Feet: {
    'None': '',
    'Standing': '==',
    'Claws': ',,-,,',
	'Paws': '(")(")',
	'Hooves': 'U-U',
	'Tentacles': '~~~',
	'Tripod': '|-|-|',
	'Multi': '||||||',
	'Boots': '[_|_]',
	'Robot': '|_|_|',
	'Webbed': '/~\\/~\\',
	'Round': 'o o',
	'Oval': '0 0',
	'Dragon': 'W^W',
	'Talons': 'Y^Y',
	'Sneakers': '[o][o]',
	'Pointy': '<_ _>',
	'Stitched': 'X~X',
	'Spikes': '^|^|^',
	'Sandals': '|-||-|',
	'Hover': '{_ _}',
	'Tiny': '. .',
	'Kama Sutra': '6 9',
	'Hooks': 'J L',
	'Pincers': 'd b',
	'Heels': 'v^v',
	'Grid': '# #',
  },
  Whiskers: {
    'None': '',
    'Head Sharp': ['>', '<'],      
    'Head Parallel': ['=', '='],
    'Snout Sharp': ['>', '<'],  
    'Snout Parallel': ['=', '='],
  },
  Wings: {
    'None': '',
    'Standard': ['//', '\\\\'],
  },
  Tail: {
    'None': '',
    'Cat': ['\\_', '  '],
    'Curl': ['@', ' '],
    'Puff': ['o', ' '],
	'Inquisitive': ['?', ' '],
	'Bobtail': ['c', ' '],
	'Nub': ['.', ' '],
	'Bobtail': ['-', ' '],
	'Sleek': ['\\', ' '],
	'Droopy': ['/', ' '],
	'Sickle': ['(', ' '],
	'Forked': ['Y', ' '],
	'Bushy': ['&', ' '],
	'Crouch': ['c', ' '],
  },
};
