// /components/Traits.js

// A library of reusable style presets for special characters.
export const specialStyles = {
  Ssmall: {textShadow: 'none', fontSize: '0.5em', position: 'relative', top: '-7px', left: '-2px'},
  Lsmall: {textShadow: 'none', fontSize: '0.55em', position: 'relative', top: '-7px', left: '-2px'},
  default: {textShadow: 'none', fontSize: '0.6em', position: 'relative', top: '-7px', left: '-2px'},
  Smedium: {textShadow: 'none', fontSize: '0.65em', position: 'relative', top: '-7px', left: '-2px'},
  Mmedium: {textShadow: 'none', fontSize: '0.7em', position: 'relative', top: '-7px', left: '-2px'},
  Lmedium: {textShadow: 'none', fontSize: '0.75em', position: 'relative', top: '-7px', left: '-2px'},
  XLmedium: {textShadow: 'none', fontSize: '0.8em', position: 'relative', top: '-7px', left: '-2px'},
  Slarge: {textShadow: 'none', fontSize: '0.85em', position: 'relative', top: '-7px', left: '-2px'},
  Mlarge: {textShadow: 'none', fontSize: '0.9em', position: 'relative', top: '-7px', left: '-2px'},
  Llarge: {textShadow: 'none', fontSize: '0.95em', position: 'relative', top: '-7px', left: '-2px'},
  XLlarge: {textShadow: 'none', fontSize: '1em', position: 'relative', top: '-7px', left: '-2px'},
  CSBowtie: {textShadow: 'none', fontSize: '1.2em', position: 'relative', top: '-2px', left: '-2px'},
  CSYinYang: {textShadow: 'none', fontSize: '0.7em', position: 'relative', top: '-5px', left: '-2px'},
  CSRadioactive: {textShadow: 'none', fontSize: '0.75em', position: 'relative', top: '-5px', left: '-2px'},
  CSBiohazard: {textShadow: 'none', fontSize: '0.65em', position: 'relative', top: '-6px', left: '-2px'},
};

// A map that links an outfit's name to a style preset from the library above.
export const outfitStyleMap = {
    'Peace': 'Mmedium',
    'Snowflake': 'Mmedium',
    'Atom': 'Lmedium',
    'Swords': 'XLmedium',
    'Biohazard': 'CSBiohazard',
    'Anchor': 'Mlarge',
    'Yin Yang': 'CSYinYang',
    'Love': 'Smedium',
    'Radioactive': 'CSRadioactive',
    'Fleur-de-lis': 'Slarge',
    'Shamrock': 'Lmedium',
    'Bowtie': 'CSBowtie',
    'Coffee': 'Lmedium',
    'Poison': 'Slarge',
    'Baseball': 'Mmedium',
    'Sun': 'Slarge',
	'Watch': 'default',
	'Scissor': 'default',
	'Female': 'Mlarge',
	'Football': 'default',
	'Recycle': 'XLmedium',
	'Male': 'Mlarge',
	'Libra': 'XLmedium',
	'Plane': 'XLmedium',
};

export const Traits = {
  Headwear: {
    'None': '',
    'Punk': '///',
    'Unicorn': '_/_',
    'Horns': 'I_I',
    'Curly': '~~~',
    'Bald Top': '¯¯¯',
	'Bald Middle': '---',
	'Bald Bottom': '___',
	'Crown': '-W-',
	'Spiky': '^^^',
	'Ninja': '===',
	'Wizard': '-^-',
	'Halo': '(o)',
	'Antenna': '_i_',
	'Antennae': '\\_/',
	'Cervine': 'Y-Y',
	'Hoot': 'v_v',
	'Feline': '^-^',
	'Loppy': 'U_U',
	'Motley': '~v~',
	'Jester': '/v\\',
	'Chef': '(@)',
	'Wreath': '(V)',
	'Candle': '|^|',
	'Nurse': '<+>',
	'Propeller': '(X)',
	'Sigil': '¯*¯',
	'Scar': '¯"¯',
	'Seer': '¯o¯',
	'Mitre': '(^)',
	'Centurion': '~I~',
	'Gears': '*x*',
	'Pinwheel Bows': '*=*',
	'Hash Bows': '#=#',
	'Twisted Bows': '%=%',
	'Headwrap': '(~)', 
  },	
  EarsTop: {
    'None': '',
    'Pointy': '^   ^',
    'Elven': '<   >',
    'Vizsla': 'V   V',
    'Feeler': 'q   p',
    'Teddy': '@   @',
	'Pikas': 'o   o',
	'Pompom': '0   0',
    'Bunny': '\\   /',
    'Droopy': '/   \\',
	'Lattice': '#   #',
	'Loppy': 'U   U',
	'Swirl': 'e   e',
	'Curl': '6   9',
	'Multi': '8   8',
	'Fluffy': '*   *',
	'Pixie': "'   '",
	'Frayed': '%   %',
	'Aqua': '≈   ≈',
	'Cobweb': 'x   x',
	'Wave': '~   ~',
	'Striped': '=   =',
  },
  EarsHead: {
    'None': '',
    'Pointy': '^   ^',
    'Elven': '<   >',
    'Vizsla': 'V   V',
    'Bunny': '\\   /',
    'Droopy': '/   \\',
	'Earmuffs': '@   @',
	'Swirl': 'e   e',
	'Earrings': ',   ,',
	'Curl': '6   9',
	'Ape': 'o   o',
	'Gauges': '0   0',
	'Loppy': 'U   U',
	'DJ': 'd   b',
	'Earbuds': 'p   q',
	'Goblin': '4   4',
	'Holes': '.   .',
	'Lattice': '#   #',
	'Pierced': ';   ;',
	'Goat': '-   -',
	'Multi': '8   8',
	'Fluffy': '*   *',
	'Pixie': "'   '",
	'Frayed': '%   %',
	'Aqua': '≈   ≈',
	'Cobweb': 'x   x',
	'Wave': '~   ~',
	'Striped': '=   =',  
  },
  Eyes: {
    'None': '',
	'Open': 'o o',
    'Glasses': 'o-o',
    'Sleepy': '- -',
    'Meth': 'o 0',
	'Close': 'u u',
    'Wide': '0 0',
	'Crazy': '6 9',
	'Monocle': 'o q',
	'Patch': 'o #',
	'Dead': 'x x',
	'Stitched': 'o x',
	'Hypnotic': '@ @',
	'Tears': '; ;',
	'Ouch': '> <',
	'Wink': 'o -',
	'Happy': '^ ^',
	'Bored': '= =',
	'Weepy': 'q p',
	'Swoon': '9 9',  
	'Bandage': '/ o',  
	'Sob': 'T T',
	'Slanted': '\\ /',
	'Sad': 'U U',
	'Serious': "' '",
	'Weary': '" "',
	'Jealous': '~ ~',
	'Multi': '8 8',
	'Awry': '> >',
	'Astonished': '* *',
	'Jackpot': '$ $',
	'Haughty': 'I I',
	'Grouchy': 'v v',
	'Anger': '` ´',
	'Dazed': '6 6',
	'Chagrin': '/ \\',
	'Doubt': '￢ ￢',
	'Cyclope': ' 0 ',
	'Remorse': 'm m',
	'Hide': '| |',
	'Anxious': 'w w',
	'Doe': 'Q Q',
	'Target': '+ +',
  },
  Mien: {
    'None': '',
    'Bit': '.',
    'Forked': 'Y',
    'Neutral': '_',
	'Smirk': ',',
	'Septum': 'I',
	'Fissure': '|',
	'Third Eye': 'o',
	'Sniffle': ';',
	'Close': 'x',
	'Beak': 'v',
	'Buttons': ':',
	'Meow': 'w',
	'Schnoz': 'U',  
  },
  Snout: {	
    'None': '',
    'Button': 'o',
    'Gator': '<=>',
    'Neutral': '_',
	'Droopy': 'Y',
	'Grin': 'W',
	'Slit': '\\≈/',  
	'Pointy': 'v',
	'Walrus': ',=,',
	'Close': 'x',
	'Jagged': 'vvv',
	'Teddy': 'I',
	'Fennec': 'V',  
	'Flare': '"',
	'Vader': '/|\\',
	'Ghoul': '^',  
	'Grazer': 'H',
	'Bill Top': '¯¯¯',
	'Bill Middle': '---',
	'Bill Bottom': '___',
	'Schnoz': 'U',
	'Fu Manchu': '/ \\',
	'Bulbous': '@',
	'Fissure': '|',
	'Smirk': ',',
	'Nostrils': '..',
	'Meh': '/',
	'Snarl': '~#~',
	'Reynard': '\\/',  
	'Double': '8',
	'Kawaii': 'owo',
	'Bit': '.',
	'Golem': '#',
	'Cantinflas': ', ,',
	'Scuba': 'd',
	'Tusk': 'J',
	'Sniffle': ';;',
	'Meow': 'w',
	'Scarecrow': '-x-',
	'Slot': '|',
	'Buttons': ':',
	'Blep': 'b',
	'Loll': 'p',
	'Android': '_T_',
	'Yell': '0',
  },
  Outfit: {
    'None': '',
    'Muscular': '=|=',
    'Suit': '\\:/',
    'Priest': '\\+/',
    'Tuxedo': '\\~/',
	'Jester Collar': '/|\\',
	'Shirt': ' :~',
	'Armor': '[#]',
	'Scarf': '_w_',
	'Tie': '_v_',
	'Medallion': '_0_',
	'Vest': 'IVI',
	'Turtleneck': '_T_',
	'V-Neck': '_V_',
	'Toga': '/~/',
	'Sweater': 'x-x',
	'Collar': '_^_',
	'Peace': '-☮-',
	'Snowflake': '~❄️~',
	'Atom': '~⚛️~',
	'Swords': '-⚔️-',
	'Biohazard': '(☣️)',
	'Anchor': 'I⚓️I',
	'Yin Yang': '(☯)',
	'Love': '-❤︎-',
	'Radioactive': '/☢️/',
	'Fleur-de-lis': '-⚜️-',
	'Shamrock': '~☘︎~',
	'Bowtie': '|⑅|',
	'Coffee': '_☕️_',
	'Poison': '\\☠/',
	'Baseball': '_⚾_',
	'Sun': '_☀_',
	'Watch': '-⌚-',
	'Scissor': '-✂-',
	'Female': '_♀️_',
	'Football': '_⚽_',
	'Recycle': '~♻️~',
	'Male': '_♂_',
	'Libra': '~⚖️~',
	'Plane': '-✈️-',
  },
  Feet: {
    'None': '',
    'Standing': '==',
    'Claws': ',,-,,',
	'Paws': '(")(")',
	'Hooves': 'U-U',
	'Tentacles': '~~~',
	'Tripod': '|-|-|',
	'Multi': '||||||',
	'Boots': '[_|_]',
	'Robot': '|_|_|',
	'Webbed': '/~\\/~\\',
	'Round': 'o o',
	'Oval': '0 0',
	'Dragon': 'W^W',
	'Talons': 'Y^Y',
	'Squeaky': '/_\\/_\\', 
	'Sneakers': '[o][o]',
	'Sled': '<_ _>',
	'Stitched': 'X~X',
	'Spikes': '^|^|^',
	'Sandals': '|-||-|',
	'Hover': '{_ _}',
	'Skis': 'V~V',  
	'Tiny': '. .',
	'Kama Sutra': '6 9',
	'Hooks': 'J L',
	'Pincers': 'd b',
	'Heels': 'v^v',
	'Grid': '# #',
  },
  Whiskers: {
    'None': '',
    'Head Sharp': ['>', '<'],      
    'Head Parallel': ['=', '='],
    'Snout Sharp': ['>', '<'],  
    'Snout Parallel': ['=', '='],
  },
  Wings: {
    'None': '',
    'Mantle': ['/', '\\'],
	'Fallen': ['~', '~'],
	'Mech': ['[', ']'],
	'Fairy': ['(', ')'],
	'Angel': ['{', '}'],
	'Bat': ['\\', '/'],
	'Chibi': ['"', '"'],
	'Shield': ['0', '0'],
	'Skeletal': ['Y', 'Y'],
	'Phoenix': ['^', '^'],
	'Vortex': ['@', '@'],
	'Arcane': ['<', '>'],
	'Fern': ['§', '§'],
  },
  Tail: {
    'None': '',
    'Slash': ['\\', ' '],
    'Curl': ['@', ' '],
    'Puff': ['o', ' '],
	'Inquisitive': ['?', ' '],
	'Screw': ['c', ' '],
	'Nub': ['.', ' '],
	'Steady': ['-', ' '],
	'Droopy': ['/', ' '],
	'Sickle': ['(', ' '],
	'Forked': ['Y', ' '],
	'Bushy': ['&', ' '],
	'Hook': ['L', ' '],
	'Serpent': ['~', ' '],
	'Trident': ['W', ' '],
	'Starburst': ['*', ' '],
	'Lasso': ['e', ' '],
  },
};
