// /components/Traits.js

// NEW: A library of reusable style presets for special characters.
export const specialStyles = {
  Ssmall: {textShadow: 'none', fontSize: '0.5em', position: 'relative', top: '-7px', left: '-2px'},
  Lsmall: {textShadow: 'none', fontSize: '0.55em', position: 'relative', top: '-7px', left: '-2px'},
  default: {textShadow: 'none', fontSize: '0.6em', position: 'relative', top: '-7px', left: '-2px'},
  Smedium: {textShadow: 'none', fontSize: '0.65em', position: 'relative', top: '-7px', left: '-2px'},
  Mmedium: {textShadow: 'none', fontSize: '0.7em', position: 'relative', top: '-7px', left: '-2px'},
  Lmedium: {textShadow: 'none', fontSize: '0.75em', position: 'relative', top: '-7px', left: '-2px'},
  XLmedium: {textShadow: 'none', fontSize: '0.8em', position: 'relative', top: '-7px', left: '-2px'},
  Slarge: {textShadow: 'none', fontSize: '0.85em', position: 'relative', top: '-7px', left: '-2px'},
  Mlarge: {textShadow: 'none', fontSize: '0.9em', position: 'relative', top: '-7px', left: '-2px'},
  Llarge: {textShadow: 'none', fontSize: '0.95em', position: 'relative', top: '-7px', left: '-2px'},
  XLlarge: {textShadow: 'none', fontSize: '1em', position: 'relative', top: '-7px', left: '-2px'},
};

// NEW: A map that links an outfit's name to a style preset from the library above.
export const outfitStyleMap = {
    'Kimono': 'default',
    'Skull': 'default',
    'Peace': 'Mmedium',
    'Farcaster': 'default',
    'Rocket': 'default',
    'Snowflake': 'Mmedium',
    'Alien': 'default',
    'Atom': 'Lmedium',
    'Swords': 'XLmedium',
    'Biohazard': 'Smedium',
    'Trident': 'default',
    'Anchor': 'Mlarge',
    'Diamond': 'default',
    'Fireball': 'default',
    'Yin Yang': 'Mmedium',
    'Crown': 'default',
    'Love': 'Smedium',
    'Radioactive': 'Lmedium',
    'Fleur-de-lis': 'Mmedium',
    'Volcano': 'default',
    'Paw': 'default',
    'Shamrock': 'Lmedium',
    'Wave': 'default',
	'Bowtie': 'XLlarge',
};

export const Traits = {
  EarsTop: {
    'None': '',
    'Pointy': '^   ^',
    'Elven': '<   >',
    'Type 3': 'v   v',
    'Antennas': 'q   p',
    'Type 5': '\\/   \\/',
    'Type 6': '/\\   /\\',
  },
  EarsHead: {
    'None': '',
    'Pointy': '^   ^',
    'Elven': '<   >',
    'Type 3': 'v   v',
    'Antennas': 'q   p',
    'Type 5': '\\/   \\/',
    'Type 6': '/\\   /\\',
  },
  Headwear: {
    'None': '',
    'Punk': '///',
    'Unicorn': '_/_',
    'Horns': '/-/',
    'Curly hair': '~~~',
    'Bald': '___',
  },
  Eyes: {
    'None': '',
    'Glasses': 'o-o',
    'Meth (Suspicious)': 'o 0',
    'Sleeping': '- -',
    'Eyes Open': 'o o',
    'Wide-Eyed': '0 0',
  },
  Nose: {
    'None': '',
    'Round': 'o',
    'Dog': 'Y',
    'Crest': '.',
    'More': '_',
  },
  Snout: {
    'None': '',
    'Normal': '---',
    'Monster': 'vvv',
    'Cigarette': '--,',
    'Wolf': 'o',
  },
  Outfit: {
    'None': '',
    'Muscular': '=|=',
    'Suit': '\\:/',
    'Priest': '\\+/',
    'Tuxedo': '\\~/',
	'Jester Collar': '/|\\',
	'Shirt': ' :~',
	'Armor': '[#]',
	'Scarf': '_w_',
	'Tie': '_v_',
	'Medallion': '_0_',
	'Vest': 'IVI',
	'Turtleneck': '_T_',
	'V-Neck': '_V_',
	'Toga': '/~/',
	'Sweater': 'x-x',
	'Collar': '_^_',
	'Kimono': '/🌸\\',
	'Skull': '\\💀/',
	'Peace': '_☮_',
	'Farcaster': '|🏰|',
	'Rocket': '/🚀/',
	'Snowflake': '_❄️_',
	'Alien': '[👾]',
	'Atom': '_⚛️_',
	'Swords': '_⚔️_',
	'Biohazard': '_☣️_',
	'Trident': '_🔱_',
	'Anchor': '_⚓️_',
	'Diamond': '_💎_',
	'Fireball': '_🔥_',
	'Yin Yang': '_☯_',
	'Crown': '_👑_',
	'Love': '_❤︎_',
	'Radioactive': '_☢️_',
	'Fleur-de-lis': '_⚜️_',
	'Volcano': '_🌋_',
	'Paw': '_🐾_',
	'Shamrock': '_☘︎_',
	'Wave': '_🌊_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
	'Bowtie': '_⑅_',
  },
  Feet: {
    'None': '',
    'Standard': '==',
    'Owl': '=,,=',
  },
  Whiskers: {
    'None': '',
    'Head Regular': ['>', '<'],
    'Head Parallel': ['=', '='],
    'Snout Regular': ['>', '<'],
    'Snout Parallel': ['=', '='],
  },
  Wings: {
    'None': '',
    'Standard': ['//', '\\\\'],
  },
  Tail: {
    'None': '',
    'Cat': ['\\_', '  '],
    'Dog': ['@', ' '],
    'Hamster': ['o', ' '],
    'Curl': ['c', ' '],
  },
};
